version: '3'
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true'
    mem_limit: 256m
    mem_reservation: 128m

  db:
    image: mongo:5.0.3  # Используем официальный образ MongoDB
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - /path/to/host/data:/data/db  # Используйте том для хранения данных
    command: ["mongod", "--noauth", "--bind_ip_all"]  # Отключаем репликацию
    mem_limit: 512m
    mem_reservation: 256m

