version: '3'
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true'
    mem_limit: 256m               # Ограничиваем максимальное использование памяти 256 MB
    mem_reservation: 128m         # Резервируем 128 MB памяти для этого контейнера

  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
    mem_limit: 512m               # Ограничиваем максимальное использование памяти 512 MB
    mem_reservation: 256m         # Резервируем 256 MB памяти для базы данных

