version: '3'
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true'
    mem_limit: 256m
    mem_reservation: 128m

  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
      # Отключение репликации
      MONGO_REPLICA_SET_KEY: ""
      MONGO_INITDB_REPLICA_SET_NAME: ""
      # Убедитесь, что MongoDB запускается без репликации
    volumes:
      - /path/to/host/data:/data/db  # Используйте том для хранения данных
    mem_limit: 512m
    mem_reservation: 256m
