name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@45.130.9.212 "cd express-api && git pull origin main && docker-compose up -d --build"

