name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Сборка Docker-образа
      - name: Build Docker Image
        run: |
          docker build -t express-app:latest .

      # 3. Подключение и деплой на сервере Ubuntu через SSH с паролем
      - name: Deploy to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          # Копирование образа на удалённый сервер
          docker save express-app:latest | bzip2 | sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bunzip2 | docker load'
          
          # Выполнение npm install на удалённом сервере и запуск нового контейнера
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          # Переход в директорию проекта (замените /app на путь к вашему проекту)
          cd /app 
          
          # Установка зависимостей
          npm install

          # Остановка старого контейнера, если он запущен
          if [ "\$(docker ps -q -f name=express-app)" ]; then
              docker stop express-app || true
              docker rm express-app || true
          fi
          
          # Запуск нового контейнера
          docker run -d --name express-app -p 3000:3000 express-app:latest
          EOF
