name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Сборка Docker-образа
      - name: Build Docker Image
        run: |
          docker build -t express-app:latest .

      # 3. Подключение и деплой на сервере Ubuntu через SSH с паролем
      - name: Deploy to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          # Копирование образа на удалённый сервер
          docker save express-app:latest | bzip2 | sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bunzip2 | docker load'
          
          # Выполнение очистки и развертывания на удалённом сервере
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          # Создание директории проекта, если она не существует
          mkdir -p /app 
          cd /app 
          
          # Копирование файлов проекта (например, с локальной машины)
          # Используйте scp или другой метод для копирования файлов в /app
          
          # Установка Node.js и npm (если они не установлены)
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Установка зависимостей
          npm install
        
          # Очистка старых Docker-образов и контейнеров
          docker system prune -af
        
          # Остановка старого контейнера, если он запущен
          if [ "\$(docker ps -q -f name=express-app)" ]; then
              docker stop express-app || true
              docker rm express-app || true
          fi
          
          # Запуск нового контейнера с проверкой ошибок
          if ! docker run -d --name express-app -p 3000:3000 express-app:latest; then
              echo "Ошибка при запуске контейнера express-app"
              exit 1
          fi
          
          EOF
