name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Сборка Docker-образа
      - name: Build Docker Image
        run: |
          docker build -t express-app:latest .

      # 3. Передача Docker-образа на сервер
      - name: Transfer Docker Image
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Starting to transfer Docker image..."
          docker save express-app:latest | bzip2 | sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          'bunzip2 | docker load && docker images | grep express-app && echo "Image successfully loaded" || { echo "Failed to load image"; exit 1; }'


      # 4. Очистка старых контейнеров и данных
      - name: Prune old Docker data
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "docker system prune -af"

      # 5. Остановка и удаление старого контейнера
      - name: Stop and remove old container
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "if [ \$(docker ps -q -f name=express-app) ]; then docker stop express-app && docker rm express-app; fi"

      # 6. Запуск нового контейнера
      - name: Run New Container with Debugging
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Starting new container with debug logs..."
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "docker run -d --name express-app -p 3000:3000 express-app:latest || { echo 'Failed to start container'; docker logs express-app || true; exit 1; }"


